spring.application.name=LeagueOfArrows
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/league_of_arrows
spring.datasource.username=postgres
spring.datasource.password=ola
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=esta-es-la-clave-para-el-lab-de-tbd-de-gestion-de-tiro-con-arco-gracias-jwt
jwt.expiration=3600000