spring.application.name=LeagueOfArrows

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/league_of_arrows
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET:esto-es-una-prueba-para-levantar-la-aplicacion-jajasaludos}
jwt.expiration=3600000
